// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CloseDatabase():Promise<void>;

export function DatabaseInfo():Promise<model.DatabaseInfo>;

export function ExportRowsToCSV(arg1:model.ExportRequest):Promise<void>;

export function GetSchema():Promise<model.SchemaInfo>;

export function GetTableRowCount(arg1:string):Promise<number>;

export function GetTableRows(arg1:model.TableRowsRequest):Promise<model.TableRowsResponse>;

export function OpenDatabase():Promise<model.DatabaseInfo>;

export function OpenDatabasePath(arg1:string):Promise<model.DatabaseInfo>;

export function RunQuery(arg1:model.QueryRequest):Promise<model.QueryResponse>;
