// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseDatabase() {
  return window['go']['backend']['App']['CloseDatabase']();
}

export function DatabaseInfo() {
  return window['go']['backend']['App']['DatabaseInfo']();
}

export function GetSchema() {
  return window['go']['backend']['App']['GetSchema']();
}

export function GetTableRowCount(arg1) {
  return window['go']['backend']['App']['GetTableRowCount'](arg1);
}

export function OpenDatabase() {
  return window['go']['backend']['App']['OpenDatabase']();
}

export function OpenDatabasePath(arg1) {
  return window['go']['backend']['App']['OpenDatabasePath'](arg1);
}
