// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1) {
  return window['go']['backend']['App']['CancelQuery'](arg1);
}

export function CloseDatabase() {
  return window['go']['backend']['App']['CloseDatabase']();
}

export function DatabaseInfo() {
  return window['go']['backend']['App']['DatabaseInfo']();
}

export function ExportRowsToCSV(arg1) {
  return window['go']['backend']['App']['ExportRowsToCSV'](arg1);
}

export function GetObjectStats(arg1) {
  return window['go']['backend']['App']['GetObjectStats'](arg1);
}

export function GetSchema() {
  return window['go']['backend']['App']['GetSchema']();
}

export function GetStatementCategories() {
  return window['go']['backend']['App']['GetStatementCategories']();
}

export function GetTableRows(arg1) {
  return window['go']['backend']['App']['GetTableRows'](arg1);
}

export function OpenDatabase() {
  return window['go']['backend']['App']['OpenDatabase']();
}

export function RunQuery(arg1) {
  return window['go']['backend']['App']['RunQuery'](arg1);
}

export function UpdateTableRow(arg1) {
  return window['go']['backend']['App']['UpdateTableRow'](arg1);
}
